# Generated by Django 3.1.1 on 2020-09-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0002_auto_20200901_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
